import { Product } from '@/types';

export const products: Product[] = [
    {
        id: 1,
        name: 'Amara Okeke',
        title: 'Hair Colorist',
        profession: 'Hair Specialist',
        category: 'Hair',
        description: 'Transform your hair with vibrant, lasting colors.',
        location: 'Lekki Kaduna',
        image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=300&fit=crop&crop=face',
        rating: 4.8,
        reviewCount: 321,
        award: '2024 Best Hair Colorist',
        specialties: [
            { name: 'Bridal Makeup', price: 'R125' },
            { name: 'Special Events', price: 'R250' },
        ],
        price: 145,
        priceRange: 'R100 - 200',
        experience: '18y exp',
        nextAvailable: 'Tomorrow 2:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#95% Trending',
        bookings: 234,
        isAvailable: true,
        distance: '1.5 Miles',
        isCertified: true,
        certificationText: 'Expert Hair Colorist',
        responseTime: 'Usually Respond within 10mins',
        workSamples: [
            'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=400&fit=crop',
            'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop',
        ],
        availability: 'Tomorrow',
        section: 'featured',
        likes: 40,
    },
    {
        id: 2,
        name: 'Chinedu Obi',
        title: 'Senior Makeup Artist',
        profession: 'Makeup Artist',
        category: 'Makeup',
        description: 'Flawless beauty enhancements for any occasion.',
        location: 'Mbape Abuja',
        image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=400&h=300&fit=crop',
        rating: 4.8,
        reviewCount: 591,
        award: '2023 Beauty Excellence Award',
        specialties: [
            { name: 'Bridal Makeup', price: 'R125' },
            { name: 'Special Events', price: 'R250' },
        ],
        price: 90,
        priceRange: 'R45 - 90',
        experience: '12y exp',
        nextAvailable: 'Today 5:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#90% Booked',
        bookings: 412,
        isAvailable: true,
        distance: '2.1 Miles',
        isCertified: true,
        certificationText: 'Master Barber Certified',
        responseTime: 'Usually Respond within 15mins',
        workSamples: [
            'https://images.unsplash.com/photo-1594736797933-d0fa0a4f5bb9?w=400&h=400&fit=crop',
            'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'featured',
        likes: 40,
    },
    {
        id: 3,
        name: 'Fatima Yusuf',
        title: 'Facialist & Skincare Expert',
        profession: 'Esthetician',
        category: 'Skin Care',
        description: 'Get glowing skin with our custom facial treatments.',
        location: 'VI Lagos',
        image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
        rating: 4.9,
        reviewCount: 410,
        award: 'Top Rated Esthetician 2022',
        specialties: [
            { name: 'Glass Skin Facial', price: 'R150' },
            { name: 'Deep Cleanse', price: 'R100' },
        ],
        price: 150,
        priceRange: 'R100 - 200',
        experience: '10y exp',
        nextAvailable: 'Monday 10:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#98% Trending',
        bookings: 326,
        isAvailable: true,
        distance: '0.8 Miles',
        isCertified: true,
        certificationText: 'Certified Esthetician',
        responseTime: 'Responds in under 5 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1589987607627-01d923d72b11?w=400&h=400&fit=crop',
        ],
        availability: 'A week',
        section: 'featured',
        likes: 40,
    },
    {
        id: 4,
        name: 'Kemi Adebayo',
        title: 'Barber & Stylist',
        profession: 'Barber',
        category: 'Locks',
        description: 'Precision cuts and stylish grooming for modern men.',
        location: 'Ikoyi Lagos',
        image: 'https://images.unsplash.com/photo-1604908554268-7f69c8a56156?w=400&h=300&fit=crop',
        rating: 4.7,
        reviewCount: 278,
        award: 'Barber of the Year 2023',
        specialties: [
            { name: 'Fade Cut', price: 'R35' },
            { name: 'Beard Styling', price: 'R20' },
        ],
        price: 45,
        priceRange: 'R30 - 60',
        experience: '8y exp',
        nextAvailable: 'Today 6:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#80% Popular',
        bookings: 200,
        isAvailable: true,
        distance: '3.5 Miles',
        isCertified: true,
        certificationText: 'Certified Master Barber',
        responseTime: 'Within 30 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1559599238-dfefb5f9d4f4?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'featured',
        likes: 40,
    },
    {
        id: 5,
        name: 'Ngozi Eze',
        title: 'Makeup & Skincare Consultant',
        profession: 'Beauty Consultant',
        category: 'Lashes',
        description: 'Tailored beauty routines and flawless makeovers.',
        location: 'Wuse Abuja',
        image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=300&fit=crop',
        rating: 5.0,
        reviewCount: 500,
        award: 'All-Round Beauty Specialist 2023',
        specialties: [
            { name: 'Everyday Glow', price: 'R85' },
            { name: 'Red Carpet Look', price: 'R250' },
        ],
        price: 180,
        priceRange: 'R85 - 250',
        experience: '15y exp',
        nextAvailable: 'Tuesday 11:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#99% Booked',
        bookings: 480,
        isAvailable: true,
        distance: '1.2 Miles',
        isCertified: true,
        certificationText: 'Beauty & Skincare Expert',
        responseTime: 'Replies in 10 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1522336572468-97b06e8ef143?w=400&h=400&fit=crop',
            'https://images.unsplash.com/photo-1612206763751-8f7193d93b1c?w=400&h=400&fit=crop',
        ],
        availability: 'Strictly Booking',
        section: 'featured',
        likes: 40,
    },
    {
        id: 6,
        name: 'Emeka Nwosu',
        title: 'Hair Colorist',
        profession: 'Hair Specialist',
        category: 'Wigs',
        description: 'Expert hair coloring for a bold new look.',
        location: 'Surulere Lagos',
        image: 'https://images.unsplash.com/photo-1596793504948-0c4c7b5e8b0b?w=400&h=300&fit=crop',
        rating: 4.6,
        reviewCount: 250,
        award: '2024 Hair Innovation Award',
        specialties: [
            { name: 'Balayage', price: 'R130' },
            { name: 'Hair Treatments', price: 'R80' },
        ],
        price: 140,
        priceRange: 'R120 - 180',
        experience: '14y exp',
        nextAvailable: 'Tomorrow 3:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#85% Trending',
        bookings: 210,
        isAvailable: true,
        distance: '2.0 Miles',
        isCertified: true,
        certificationText: 'Certified Hair Colorist',
        responseTime: 'Replies in 12 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1578637387939-43c25d02b8d9?w=400&h=400&fit=crop',
        ],
        availability: 'Tomorrow',
        section: 'featured',
        likes: 40,
    },
    {
        id: 7,
        name: 'Zainab Musa',
        title: 'Nail Technician',
        profession: 'Nail Artist',
        category: 'Nails',
        description: 'Stunning nail designs for every occasion.',
        location: 'Garki Abuja',
        image: 'https://images.unsplash.com/photo-1519415510236-7184a0b1b709?w=400&h=300&fit=crop',
        rating: 4.9,
        reviewCount: 380,
        award: '2023 Nail Art Excellence',
        specialties: [
            { name: 'Acrylic Nails', price: 'R60' },
            { name: 'Gel Manicure', price: 'R45' },
        ],
        price: 50,
        priceRange: 'R40 - 70',
        experience: '9y exp',
        nextAvailable: 'Today 4:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#92% Booked',
        bookings: 300,
        isAvailable: true,
        distance: '1.8 Miles',
        isCertified: true,
        certificationText: 'Certified Nail Technician',
        responseTime: 'Replies in 8 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1598966758796-c1b7b6d96e2f?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'featured',
        likes: 40,
    },
    {
        id: 8,
        name: 'Chukwuemeka Ade',
        title: 'Skincare Specialist',
        profession: 'Esthetician',
        category: 'Skin Care',
        description: 'Personalized skincare for radiant results.',
        location: 'Ikeja Lagos',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop',
        rating: 4.7,
        reviewCount: 290,
        award: '2022 Skincare Specialist Award',
        specialties: [
            { name: 'HydraFacial', price: 'R120' },
            { name: 'Chemical Peel', price: 'R90' },
        ],
        price: 110,
        priceRange: 'R80 - 150',
        experience: '11y exp',
        nextAvailable: 'Monday 9:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#90% Trending',
        bookings: 260,
        isAvailable: true,
        distance: '2.5 Miles',
        isCertified: true,
        certificationText: 'Certified Esthetician',
        responseTime: 'Replies in 15 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=400&fit=crop',
        ],
        availability: 'A week',
        section: 'featured',
        likes: 40,
    },
    {
        id: 9,
        name: 'Funmi Alabi',
        title: 'Makeup Artist',
        profession: 'Makeup Artist',
        category: 'Makeup',
        description: 'Glamorous makeup for events and photoshoots.',
        location: 'Asokoro Abuja',
        image: 'https://images.unsplash.com/photo-1576176539998-6f24b9c7c0c5?w=400&h=300&fit=crop',
        rating: 4.8,
        reviewCount: 340,
        award: '2023 Makeup Artist of the Year',
        specialties: [
            { name: 'Evening Makeup', price: 'R100' },
            { name: 'Bridal Makeup', price: 'R200' },
        ],
        price: 120,
        priceRange: 'R90 - 150',
        experience: '13y exp',
        nextAvailable: 'Tuesday 10:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#95% Booked',
        bookings: 320,
        isAvailable: true,
        distance: '1.0 Miles',
        isCertified: true,
        certificationText: 'Certified Makeup Artist',
        responseTime: 'Replies in 10 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1519748771451-a94c1868282b?w=400&h=400&fit=crop',
        ],
        availability: 'Strictly Booking',
        section: 'featured',
        likes: 40,
    },
    {
        id: 10,
        name: 'Tolu Afolabi',
        title: 'Hair Stylist',
        profession: 'Hair Specialist',
        category: 'Hair',
        description: 'Creative hair styling for all hair types.',
        location: 'Yaba Lagos',
        image: 'https://images.unsplash.com/photo-1610878180933-123728745d22?w=400&h=300&fit=crop',
        rating: 4.9,
        reviewCount: 400,
        award: '2024 Hair Stylist Award',
        specialties: [
            { name: 'Braiding', price: 'R70' },
            { name: 'Hair Coloring', price: 'R120' },
        ],
        price: 100,
        priceRange: 'R80 - 140',
        experience: '10y exp',
        nextAvailable: 'Tomorrow 1:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#97% Trending',
        bookings: 350,
        isAvailable: true,
        distance: '1.3 Miles',
        isCertified: true,
        certificationText: 'Certified Hair Stylist',
        responseTime: 'Replies in 5 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1578637387939-43c25d02b8d9?w=400&h=400&fit=crop',
        ],
        availability: 'Tomorrow',
        section: 'featured',
        likes: 40,
    },
    {
        id: 11,
        name: 'Ifeanyi Okonkwo',
        title: 'Barber',
        profession: 'Barber',
        category: 'Locks',
        description: 'Classic and modern cuts for men.',
        location: 'Maitama Abuja',
        image: 'https://images.unsplash.com/photo-1595475038784-b3c4c36b43f0?w=400&h=300&fit=crop',
        rating: 4.6,
        reviewCount: 230,
        award: '2023 Top Barber',
        specialties: [
            { name: 'Classic Cut', price: 'R30' },
            { name: 'Beard Trim', price: 'R15' },
        ],
        price: 40,
        priceRange: 'R25 - 50',
        experience: '7y exp',
        nextAvailable: 'Today 7:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#85% Popular',
        bookings: 180,
        isAvailable: true,
        distance: '2.8 Miles',
        isCertified: true,
        certificationText: 'Certified Barber',
        responseTime: 'Replies in 20 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1605497788044-5a32c7078406?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 12,
        name: 'Bisola Adesina',
        title: 'Skincare Consultant',
        profession: 'Esthetician',
        category: 'Skin Care',
        description: 'Custom skincare solutions for all skin types.',
        location: 'Ajah Lagos',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop',
        rating: 4.8,
        reviewCount: 310,
        award: '2022 Skincare Expert',
        specialties: [
            { name: 'Anti-Aging Facial', price: 'R130' },
            { name: 'Acne Treatment', price: 'R90' },
        ],
        price: 120,
        priceRange: 'R100 - 150',
        experience: '12y exp',
        nextAvailable: 'Monday 11:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#90% Trending',
        bookings: 280,
        isAvailable: true,
        distance: '2.2 Miles',
        isCertified: true,
        certificationText: 'Certified Esthetician',
        responseTime: 'Replies in 10 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=400&fit=crop',
        ],
        availability: 'A week',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 13,
        name: 'Uche Nnamdi',
        title: 'Makeup Artist',
        profession: 'Makeup Artist',
        category: 'Makeup',
        description: 'Bold and beautiful makeup for any event.',
        location: 'Gwarinpa Abuja',
        image: 'https://images.unsplash.com/photo-1519748771451-a94c1868282b?w=400&h=300&fit=crop',
        rating: 4.7,
        reviewCount: 270,
        award: '2023 Makeup Specialist',
        specialties: [
            { name: 'Event Makeup', price: 'R110' },
            { name: 'Bridal Makeup', price: 'R180' },
        ],
        price: 130,
        priceRange: 'R100 - 160',
        experience: '10y exp',
        nextAvailable: 'Tuesday 12:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#92% Booked',
        bookings: 290,
        isAvailable: true,
        distance: '1.9 Miles',
        isCertified: true,
        certificationText: 'Certified Makeup Artist',
        responseTime: 'Replies in 15 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1576176539998-6f24b9c7c0c5?w=400&h=400&fit=crop',
        ],
        availability: 'Strictly Booking',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 14,
        name: 'Aisha Mohammed',
        title: 'Nail Technician',
        profession: 'Nail Artist',
        category: 'Nails',
        description: 'Creative nail art and manicures.',
        location: 'Banana Island Lagos',
        image: 'https://images.unsplash.com/photo-1598966758796-c1b7b6d96e2f?w=400&h=300&fit=crop',
        rating: 4.9,
        reviewCount: 350,
        award: '2024 Nail Art Award',
        specialties: [
            { name: 'Gel Nails', price: 'R50' },
            { name: 'Nail Art', price: 'R30' },
        ],
        price: 45,
        priceRange: 'R30 - 60',
        experience: '8y exp',
        nextAvailable: 'Today 3:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#95% Trending',
        bookings: 310,
        isAvailable: true,
        distance: '1.6 Miles',
        isCertified: true,
        certificationText: 'Certified Nail Technician',
        responseTime: 'Replies in 7 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1519415510236-7184a0b1b709?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 15,
        name: 'Chidi Okoye',
        title: 'Hair Stylist',
        profession: 'Hair Specialist',
        category: 'Hair',
        description: 'Trendy haircuts and styling for all.',
        location: 'Magodo Lagos',
        image: 'https://images.unsplash.com/photo-1596793504948-0c4c7b5e8b0b?w=400&h=300&fit=crop',
        rating: 4.8,
        reviewCount: 320,
        award: '2023 Hair Stylist Award',
        specialties: [
            { name: 'Haircuts', price: 'R50' },
            { name: 'Coloring', price: 'R100' },
        ],
        price: 80,
        priceRange: 'R60 - 120',
        experience: '9y exp',
        nextAvailable: 'Tomorrow 11:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#90% Booked',
        bookings: 270,
        isAvailable: true,
        distance: '2.3 Miles',
        isCertified: true,
        certificationText: 'Certified Hair Stylist',
        responseTime: 'Replies in 10 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1578637387939-43c25d02b8d9?w=400&h=400&fit=crop',
        ],
        availability: 'Tomorrow',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 16,
        name: 'Bola Adekunle',
        title: 'Skincare Expert',
        profession: 'Esthetician',
        category: 'Skin Care',
        description: 'Advanced skincare treatments for glowing skin.',
        location: 'Jabi Abuja',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop',
        rating: 4.7,
        reviewCount: 280,
        award: '2022 Skincare Specialist',
        specialties: [
            { name: 'Microdermabrasion', price: 'R110' },
            { name: 'Facial', price: 'R80' },
        ],
        price: 100,
        priceRange: 'R80 - 130',
        experience: '10y exp',
        nextAvailable: 'Monday 12:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#88% Trending',
        bookings: 250,
        isAvailable: true,
        distance: '2.0 Miles',
        isCertified: true,
        certificationText: 'Certified Esthetician',
        responseTime: 'Replies in 15 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=400&fit=crop',
        ],
        availability: 'A week',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 17,
        name: 'Efe Oghene',
        title: 'Makeup Artist',
        profession: 'Makeup Artist',
        category: 'Makeup',
        description: 'Stunning makeup looks for all occasions.',
        location: 'Lekki Lagos',
        image: 'https://images.unsplash.com/photo-1519748771451-a94c1868282b?w=400&h=300&fit=crop',
        rating: 4.9,
        reviewCount: 360,
        award: '2024 Makeup Excellence',
        specialties: [
            { name: 'Bridal Makeup', price: 'R150' },
            { name: 'Event Makeup', price: 'R100' },
        ],
        price: 120,
        priceRange: 'R90 - 150',
        experience: '11y exp',
        nextAvailable: 'Tuesday 1:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#94% Booked',
        bookings: 330,
        isAvailable: true,
        distance: '1.7 Miles',
        isCertified: true,
        certificationText: 'Certified Makeup Artist',
        responseTime: 'Replies in 8 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1576176539998-6f24b9c7c0c5?w=400&h=400&fit=crop',
        ],
        availability: 'Strictly Booking',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 18,
        name: 'Temi Olatunde',
        title: 'Nail Technician',
        profession: 'Nail Artist',
        category: 'Nails',
        description: 'Elegant nail designs and treatments.',
        location: 'Ikoyi Lagos',
        image: 'https://images.unsplash.com/photo-1598966758796-c1b7b6d96e2f?w=400&h=300&fit=crop',
        rating: 4.8,
        reviewCount: 300,
        award: '2023 Nail Art Specialist',
        specialties: [
            { name: 'Acrylic Nails', price: 'R55' },
            { name: 'Gel Manicure', price: 'R40' },
        ],
        price: 50,
        priceRange: 'R35 - 65',
        experience: '7y exp',
        nextAvailable: 'Today 5:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#90% Trending',
        bookings: 280,
        isAvailable: true,
        distance: '1.5 Miles',
        isCertified: true,
        certificationText: 'Certified Nail Technician',
        responseTime: 'Replies in 10 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1519415510236-7184a0b1b709?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 19,
        name: 'Obinna Eze',
        title: 'Barber',
        profession: 'Barber',
        category: 'Locks',
        description: 'Sharp cuts and grooming for modern men.',
        location: 'Wuse Abuja',
        image: 'https://images.unsplash.com/photo-1595475038784-b3c4c36b43f0?w=400&h=300&fit=crop',
        rating: 4.7,
        reviewCount: 260,
        award: '2023 Barber Award',
        specialties: [
            { name: 'Fade Cut', price: 'R35' },
            { name: 'Beard Styling', price: 'R20' },
        ],
        price: 45,
        priceRange: 'R30 - 60',
        experience: '8y exp',
        nextAvailable: 'Today 6:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#85% Popular',
        bookings: 220,
        isAvailable: true,
        distance: '2.4 Miles',
        isCertified: true,
        certificationText: 'Certified Master Barber',
        responseTime: 'Replies in 20 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1605497788044-5a32c7078406?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 20,
        name: 'Adanna Ibe',
        title: 'Skincare Consultant',
        profession: 'Esthetician',
        category: 'Skin Care',
        description: 'Tailored skincare for radiant results.',
        location: 'VI Lagos',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop',
        rating: 4.8,
        reviewCount: 310,
        award: '2022 Skincare Excellence',
        specialties: [
            { name: 'HydraFacial', price: 'R120' },
            { name: 'Chemical Peel', price: 'R90' },
        ],
        price: 110,
        priceRange: 'R80 - 150',
        experience: '11y exp',
        nextAvailable: 'Monday 10:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#90% Trending',
        bookings: 290,
        isAvailable: true,
        distance: '1.8 Miles',
        isCertified: true,
        certificationText: 'Certified Esthetician',
        responseTime: 'Replies in 15 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=400&fit=crop',
        ],
        availability: 'A week',
        section: 'top_rated',
        likes: 40,
    },
    {
        id: 21,
        name: 'Chiamaka Ndu',
        title: 'Hair Colorist',
        profession: 'Hair Specialist',
        category: 'Hair',
        description: 'Vibrant hair coloring for a stunning look.',
        location: 'Lekki Kaduna',
        image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=300&fit=crop',
        rating: 4.8,
        reviewCount: 330,
        award: '2024 Hair Colorist Award',
        specialties: [
            { name: 'Balayage', price: 'R140' },
            { name: 'Hair Treatments', price: 'R90' },
        ],
        price: 150,
        priceRange: 'R120 - 180',
        experience: '15y exp',
        nextAvailable: 'Tomorrow 2:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#95% Trending',
        bookings: 240,
        isAvailable: true,
        distance: '1.5 Miles',
        isCertified: true,
        certificationText: 'Expert Hair Colorist',
        responseTime: 'Replies in 10 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=400&fit=crop',
        ],
        availability: 'Tomorrow',
        section: 'online',
        likes: 40,
    },
    {
        id: 22,
        name: 'Yemi Ogunleye',
        title: 'Makeup Artist',
        profession: 'Makeup Artist',
        category: 'Makeup',
        description: 'Flawless makeup for weddings and events.',
        location: 'Mbape Abuja',
        image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=400&h=300&fit=crop',
        rating: 4.9,
        reviewCount: 600,
        award: '2023 Beauty Award',
        specialties: [
            { name: 'Bridal Makeup', price: 'R130' },
            { name: 'Special Events', price: 'R260' },
        ],
        price: 100,
        priceRange: 'R50 - 100',
        experience: '13y exp',
        nextAvailable: 'Today 4:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#92% Booked',
        bookings: 420,
        isAvailable: true,
        distance: '2.0 Miles',
        isCertified: true,
        certificationText: 'Certified Makeup Artist',
        responseTime: 'Replies in 15 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1594736797933-d0fa0a4f5bb9?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'online',
        likes: 40,
    },
    {
        id: 23,
        name: 'Halima Sani',
        title: 'Skincare Expert',
        profession: 'Esthetician',
        category: 'Skin Care',
        description: 'Custom facials for radiant, healthy skin.',
        location: 'VI Lagos',
        image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
        rating: 4.9,
        reviewCount: 420,
        award: '2022 Top Esthetician',
        specialties: [
            { name: 'Glass Skin Facial', price: 'R160' },
            { name: 'Deep Cleanse', price: 'R110' },
        ],
        price: 160,
        priceRange: 'R110 - 210',
        experience: '11y exp',
        nextAvailable: 'Monday 11:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#98% Trending',
        bookings: 340,
        isAvailable: true,
        distance: '0.9 Miles',
        isCertified: true,
        certificationText: 'Certified Esthetician',
        responseTime: 'Replies in 5 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1589987607627-01d923d72b11?w=400&h=400&fit=crop',
        ],
        availability: 'A week',
        section: 'online',
        likes: 40,
    },
    {
        id: 24,
        name: 'Segun Adeyemi',
        title: 'Barber',
        profession: 'Barber',
        category: 'Locks',
        description: 'Precision grooming and stylish cuts.',
        location: 'Ikoyi Lagos',
        image: 'https://images.unsplash.com/photo-1604908554268-7f69c8a56156?w=400&h=300&fit=crop',
        rating: 4.7,
        reviewCount: 290,
        award: '2023 Barber of the Year',
        specialties: [
            { name: 'Fade Cut', price: 'R40' },
            { name: 'Beard Styling', price: 'R25' },
        ],
        price: 50,
        priceRange: 'R35 - 65',
        experience: '9y exp',
        nextAvailable: 'Today 5:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#85% Popular',
        bookings: 210,
        isAvailable: true,
        distance: '3.0 Miles',
        isCertified: true,
        certificationText: 'Certified Master Barber',
        responseTime: 'Replies in 25 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1559599238-dfefb5f9d4f4?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'online',
        likes: 40,
    },
    {
        id: 25,
        name: 'Nkechi Umeh',
        title: 'Beauty Consultant',
        profession: 'Beauty Consultant',
        category: 'Lashes',
        description: 'Custom beauty routines and stunning makeovers.',
        location: 'Wuse Abuja',
        image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=300&fit=crop',
        rating: 5.0,
        reviewCount: 510,
        award: '2023 Beauty Specialist',
        specialties: [
            { name: 'Everyday Glow', price: 'R90' },
            { name: 'Red Carpet Look', price: 'R260' },
        ],
        price: 190,
        priceRange: 'R90 - 260',
        experience: '16y exp',
        nextAvailable: 'Tuesday 12:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#99% Booked',
        bookings: 490,
        isAvailable: true,
        distance: '1.3 Miles',
        isCertified: true,
        certificationText: 'Beauty & Skincare Expert',
        responseTime: 'Replies in 10 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1522336572468-97b06e8ef143?w=400&h=400&fit=crop',
        ],
        availability: 'Strictly Booking',
        section: 'online',
        likes: 40,
    },
    {
        id: 26,
        name: 'Damilola Afolabi',
        title: 'Nail Technician',
        profession: 'Nail Artist',
        category: 'Nails',
        description: 'Creative nail designs for all styles.',
        location: 'Surulere Lagos',
        image: 'https://images.unsplash.com/photo-1519415510236-7184a0b1b709?w=400&h=300&fit=crop',
        rating: 4.8,
        reviewCount: 360,
        award: '2024 Nail Art Award',
        specialties: [
            { name: 'Acrylic Nails', price: 'R60' },
            { name: 'Gel Manicure', price: 'R45' },
        ],
        price: 50,
        priceRange: 'R40 - 70',
        experience: '8y exp',
        nextAvailable: 'Today 4:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#92% Trending',
        bookings: 300,
        isAvailable: true,
        distance: '1.8 Miles',
        isCertified: true,
        certificationText: 'Certified Nail Technician',
        responseTime: 'Replies in 8 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1598966758796-c1b7b6d96e2f?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'online',
        likes: 40,
    },
    {
        id: 27,
        name: 'Chukwuma Okafor',
        title: 'Skincare Specialist',
        profession: 'Esthetician',
        category: 'Skin Care',
        description: 'Personalized skincare for radiant results.',
        location: 'Ikeja Lagos',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop',
        rating: 4.7,
        reviewCount: 290,
        award: '2022 Skincare Specialist Award',
        specialties: [
            { name: 'HydraFacial', price: 'R120' },
            { name: 'Chemical Peel', price: 'R90' },
        ],
        price: 110,
        priceRange: 'R80 - 150',
        experience: '11y exp',
        nextAvailable: 'Monday 9:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#90% Trending',
        bookings: 260,
        isAvailable: true,
        distance: '2.5 Miles',
        isCertified: true,
        certificationText: 'Certified Esthetician',
        responseTime: 'Replies in 15 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=400&fit=crop',
        ],
        availability: 'A week',
        section: 'online',
        likes: 40,
    },
    {
        id: 28,
        name: 'Funke Adeyemo',
        title: 'Makeup Artist',
        profession: 'Makeup Artist',
        category: 'Makeup',
        description: 'Glamorous makeup for events and photoshoots.',
        location: 'Asokoro Abuja',
        image: 'https://images.unsplash.com/photo-1576176539998-6f24b9c7c0c5?w=400&h=300&fit=crop',
        rating: 4.8,
        reviewCount: 340,
        award: '2023 Makeup Artist of the Year',
        specialties: [
            { name: 'Evening Makeup', price: 'R100' },
            { name: 'Bridal Makeup', price: 'R200' },
        ],
        price: 120,
        priceRange: 'R90 - 150',
        experience: '13y exp',
        nextAvailable: 'Tuesday 10:00 AM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#95% Booked',
        bookings: 320,
        isAvailable: true,
        distance: '1.0 Miles',
        isCertified: true,
        certificationText: 'Certified Makeup Artist',
        responseTime: 'Replies in 10 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1519748771451-a94c1868282b?w=400&h=400&fit=crop',
        ],
        availability: 'Strictly Booking',
        section: 'online',
        likes: 40,
    },
    {
        id: 29,
        name: 'Tobi Afolayan',
        title: 'Hair Stylist',
        profession: 'Hair Specialist',
        category: 'Hair',
        description: 'Creative hair styling for all hair types.',
        location: 'Yaba Lagos',
        image: 'https://images.unsplash.com/photo-1596793504948-0c4c7b5e8b0b?w=400&h=300&fit=crop',
        rating: 4.9,
        reviewCount: 400,
        award: '2024 Hair Stylist Award',
        specialties: [
            { name: 'Braiding', price: 'R70' },
            { name: 'Hair Coloring', price: 'R120' },
        ],
        price: 100,
        priceRange: 'R80 - 140',
        experience: '10y exp',
        nextAvailable: 'Tomorrow 1:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: false,
        badge: '#97% Trending',
        bookings: 350,
        isAvailable: true,
        distance: '1.3 Miles',
        isCertified: true,
        certificationText: 'Certified Hair Stylist',
        responseTime: 'Replies in 5 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1578637387939-43c25d02b8d9?w=400&h=400&fit=crop',
        ],
        availability: 'Tomorrow',
        section: 'online',
        likes: 40,
    },
    {
        id: 30,
        name: 'Ifeoma Nwankwo',
        title: 'Nail Technician',
        profession: 'Nail Artist',
        category: 'Nails',
        description: 'Stunning nail designs for every occasion.',
        location: 'Garki Abuja',
        image: 'https://images.unsplash.com/photo-1519415510236-7184a0b1b709?w=400&h=300&fit=crop',
        rating: 4.9,
        reviewCount: 380,
        award: '2023 Nail Art Excellence',
        specialties: [
            { name: 'Acrylic Nails', price: 'R60' },
            { name: 'Gel Manicure', price: 'R45' },
        ],
        price: 50,
        priceRange: 'R40 - 70',
        experience: '9y exp',
        nextAvailable: 'Today 4:00 PM',
        duration: '1h 30m',
        time: '10:00 AM',
        favorite: true,
        badge: '#92% Booked',
        bookings: 300,
        isAvailable: true,
        distance: '1.8 Miles',
        isCertified: true,
        certificationText: 'Certified Nail Technician',
        responseTime: 'Replies in 8 mins',
        workSamples: [
            'https://images.unsplash.com/photo-1598966758796-c1b7b6d96e2f?w=400&h=400&fit=crop',
        ],
        availability: 'Today',
        section: 'online',
        likes: 40,
    },
];
